module.exports = {
  docs: [
    'meta/glossary',
    { type: 'category', label: 'Quick Guides', collapsed: false, items: [
      'quick-guides/choosing-a-sealer',
      'quick-guides/troubleshooting-efflorescence'
    ]},
    { type: 'autogenerated', dirName: '.' }
  ]
};
