name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-deploy:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    env:
      ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
      ALGOLIA_SEARCH_API_KEY: ${{ secrets.ALGOLIA_SEARCH_API_KEY }}
      ALGOLIA_INDEX_NAME: ${{ secrets.ALGOLIA_INDEX_NAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20'

      - name: Install dependencies (use npm ci if package-lock.json exists)
        id: install
        run: |
          if [ -f package-lock.json ]; then
            echo "package-lock.json found — running 'npm ci' for reproducible install"
            npm ci
          else
            echo "No package-lock.json — falling back to 'npm install'"
            npm install
          fi
        env:
          npm_config_loglevel: verbose

      - name: Show Node & npm versions
        run: |
          node --version
          npm --version

      - name: Build
        run: npm run build

      - name: Print npm debug log (on failure)
        if: ${{ failure() && steps.install.outcome == 'failure' }}
        run: |
          LOGFILE=$(ls -t /home/runner/.npm/_logs/*-debug-*.log 2>/dev/null | head -n1 || true)
          if [ -n "$LOGFILE" ]; then
            echo "---- NPM DEBUG LOG ($LOGFILE) ----"
            sed -n '1,400p' "$LOGFILE" || true
          else
            echo "No npm debug log found."
          fi

      - name: Publish to GitHub Pages
        if: ${{ success() }}
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build

      - name: Upload npm logs artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: npm-logs
          path: /home/runner/.npm/_logs/
          if-no-files-found: ignore
